### ISSUE TITLE
Draft "Contact Us"

### ISSUE THREAD

**Issue by cmatta2** [therabble/sustain-care.org#33]
This is just a test for the projects

**Comment by wrolson22** [comment]
This has been created on the SC google drive folder under "Contact Page." @DonG-D-MSN to review since he is the point of contact. Comments are listed on the page.

**Comment by prestonaustin** [comment]
So, the easiest way to handle review would be to check in the draft here in github, and request a review, as that's trackable in here. I'm happy to show how that works, just reach out. I'll make an example that proposes to close this issue.

**Comment by prestonaustin** [comment]
Here's how I created the above open pull request to close this issue with a deliverable, and assigned it to @cmatta2 for review:

ON THE MAIN SUSTAIN-CARE.ORG GITHUB PAGE, CREATE NEW FILE:
<img width="124" alt="Screen Shot 2020-05-01 at 5 27 59 PM" src="https://user-images.githubusercontent.com/50559/80846210-25fd3b80-8bd1-11ea-9b9a-5bf948227afd.png">

THAT GETS YOU THIS, I ADDED A DIRECTORY AND THE FILE AT THE TOP, AND TOLD IT TO CREATE A NEW BRANCH WHICH HOLDS THIS PROPOSED WORK.
<img width="833" alt="Screen Shot 2020-05-01 at 5 24 01 PM" src="https://user-images.githubusercontent.com/50559/80846272-44fbcd80-8bd1-11ea-8dcf-761d8e0cf165.png">

THAT TAKES ME TO HERE, WHERE I CAN PROPOSE THIS WORK BE INCLUDED IN THE PROJECT, AND ASK FOR A REVIEWER TO ACCEPT/REJECT IT
<img width="817" alt="Screen Shot 2020-05-01 at 5 24 40 PM" src="https://user-images.githubusercontent.com/50559/80846344-812f2e00-8bd1-11ea-9c12-e9915dc01906.png">

BECAUSE I SAID IT CLOSES #33 THE SYSTEM LINKS IT TO THE ISSUE, YOU CAN SEE THAT AFTER I OPEN THE PULL REQUEST, IN THE LOWER RIGHT COLUMN:
<img width="823" alt="Screen Shot 2020-05-01 at 5 26 15 PM" src="https://user-images.githubusercontent.com/50559/80846401-aae85500-8bd1-11ea-8609-538e6c293e44.png">

IF THAT PR IS MERGED, THIS ISSUE WILL CLOSE ITSELF, IF THAT PR IS REJECTED FOR FURTHER WORK OR DELETED WITHOUT MERGING IT, THIS PR WILL REMAIN OPEN.

**Comment by prestonaustin** [comment]
@cmatta2  - adding a comment to a closed issue here for you just to show how the fake review closed it out. You can reopen this issue if you want to still use it for a real contact us review that isn't done yet :)

IN RECEIPT OF YOUR FAKE REVIEW APPROVING MY CHANGES, I MERGED THEM TO MASTER AND CLOSED THE PR AND DELETED IT, WHICH CLOSED THE ISSUE ABOVE, LIKE SO...

OVER ON THE PR https://github.com/therabble/sustain-care.org/pull/40 I SEE YOUR APPROVAL AND SO I "MERGE PULL REQUEST" (I HAVE AUTHORITY TO DO THIS BECAUSE I'M A MAINTAINER, AS IS EVERYONE IN THE GROUP, BUT SOMEONE FROM ANOTHER GROUP COULD PROPOSE A PR FROM OUTSIDE AND WE COULD STILL DO THIS MERGE - THEY CANNOT)
<img width="1050" alt="Screen Shot 2020-05-02 at 5 22 06 PM" src="https://user-images.githubusercontent.com/50559/80893631-cd45a580-8c99-11ea-8626-ca6213762606.png">

THEN I CONFIRM THE MERGE WITH A MERGE MESSAGE, THIS IS THE DEFAULT - I COULD ADD MORE ISSUES THIS CLOSES WITH "closes # <-number of an issue after # >" TYPE MESSAGES HERE.
<img width="778" alt="Screen Shot 2020-05-02 at 5 21 23 PM" src="https://user-images.githubusercontent.com/50559/80893621-b56e2180-8c99-11ea-9653-9c2f6aaa55d9.png">

AFTER THE PR IS CLOSED, I HAVE THE OPTION TO DELETE THE BRANCH. I WOULD NOT DO THAT IF I THOUGHT MORE WORK WAS LIKELY ON THIS RIGHT AWAY, BUT IN MOST CASES DELETING BRANCHES IS THE WAY TO GO ONCE MERGED. THAT WAY YOUR NEW WORK IS BASED ON THE CURRENT MASTER NOT SOMETHING GETTING FURTHER OUT OF DATE WITH OTHERS' CHANGES.
<img width="1031" alt="Screen Shot 2020-05-02 at 5 22 49 PM" src="https://user-images.githubusercontent.com/50559/80893710-5f4dae00-8c9a-11ea-9ba6-444fec588374.png">

SO, HERE IT IS, PR MERGED AND BRANCH DELETED. FOR A WHILE THIS IS EASILY UNDONE, BUT AFTER MUCH ELSE HAPPENS UNDOING IT WOULD GET TRICKY IF NEW WORK DEPENDS ON THIS MERGED CHANGE.
<img width="1043" alt="Screen Shot 2020-05-02 at 5 22 35 PM" src="https://user-images.githubusercontent.com/50559/80893688-2f9ea600-8c9a-11ea-816f-9d33bdff85d5.png">
