### ISSUE TITLE
Test the Initiative Registry Form

### ISSUE THREAD

**Issue by cmatta2** [therabble/sustain-care.org#42]
Add an Initiative to the initiative capture form

**Comment by cmatta2** [comment]
Link of the form is in the "Slack - Technical Model"

**Comment by wrolson22** [comment]
@mfeif , I tried to go to the form and test it out but it says it is no longer accepting responses. I also saw there were zero recorded responses on the form. Is there a updated form you would like us to use? Just want to make sure I am not missing something.

**Comment by jchuran** [comment]
@mfeif , I may have gone too far, but I activated the google form and sent out links to the other assignees in this issue.  I entered made up info into the form and didn't have any issues.  Hopefully you can take a look at what it looks like on the back end. 

My only critic was that the paragraph explaining "Your Fundraising Addresses" was written in a way that was confusing for me to comprehend.  That could just be me.  Normally I am the type of person that doesn't even read those sort of directions though.  ¯\_(ツ)_/¯ 

I received the follow up email.

Let me know if there is anything else I can do to help it along.

**Comment by mfeif** [comment]
Sorry @wrolson22, I didn't see that you tagged me. I'm not sure where those notifications are going. Probably email hell; I'll make sure they don't get filtered.

I'm not sure what you saw; it's possible you tried to fill in the form in editable mode; I made an edit in the Slack message about that to help others. This [link is for actually filling in the form itself](https://docs.google.com/forms/d/e/1FAIpQLSc82mkVbbPQAgtRiGfNJy1CvVD3bPAm9U2GXECB9sL4pM0fGw/viewform?usp=sf_link), and is ok to share, since it's just to fill-in and doesn't give access to the back end or changing the form. There's one response there now, but that seems to be Jon :-).

@jchuran, good work, thanks. I'm not sure how/why it wasn't "active". This stuff is confusing. I agree on the writing there; I've asked people to look at that over in #35. Thanks Jon! I'll remove you from this one.

**Comment by wrolson22** [comment]
I just went through and tried responding to each comment with a real project but didn't send it through with the information just to protect that project's ideas and all. With that, I think the information asked is great. Just a few comments:

- How formal/informal do we want to be on the submission page? I feel that a couple of the sub comments were a little informal such as "optional, won’t be published, might use it to reach you with something urgent and cool" for the phone number question. 

My only concern is that some people may not take the submission as serious as we would like. I do not personally mind this wording at all and I would enjoy it but I am just trying to think of the broader demographic.

**Comment by prestonaustin** [comment]
@wrolson22 Happy to go in and reword, but I think we should launch with the forum as is almost regardless of what feedback we develop, and then act on our feedback in context of a live implement that is being used by people who aren't participants in our team process.

To directly address the feedback though, I think you are absolutely correct. I think the voice is potentially off putting for people who expect a high level of formality. I tend to err in that direction, as well as allowing technical and design and usability hurdles to be higher in initial deploys, to find the right level to sustain for things.

If we were building a bridge across a chasm for a village to escape a volcano I would want to make sure that the bridge didn't break during the single exodus where people were walking across it. Prudence under the circumstances would dictate that the bridge builders certify their emergency bridges good enough by walking across it first in a group. But in this case what we are doing is building a strut for an experimental sort of bicycle, and we want the strut to be as light as possible, so we should start with a lightweight strut that's easy to install and work our way towards strong enough by crashing the bicycle multiple times because our weak poorly installed strut failed us until we have one that is just strong enough and just well enough installed.

Stated differently, since the work we're doing is important fundamentally, and having somebody who we are paying to fill out this form find it unpleasant and tell us why, or finish it in a way that we know things based on the response about how we should make the form better, since we don't actually know much about what people in the world really need us to do to make it approachable and palatable and usable for them, we should focus on getting it out there with minimal quality of design, minimal work on usability, minimal focus on consistent language, minimal quality of brand, minimal consistency in communications, minimal debugging of code, and maximized hassle for the potential perspective user. I want, and I think we should all want, to discover what we actually need to do by failing to succeed when we didn't do it yet, and iterating quickly from there towards a level that does meet people's needs on each concern. We should do this in series, not in parallel with the entire universe of people we might want to reach, but there is a reason why I think we should pay people to fill out our forms, they are in my design frame provisional, all of our work should be assumed to be junk until a bunch of people who aren't us have filled them out so that we can respond to what happens and make them right if they need to be different.

That may sound either lazy or crazy, but anything beyond what we have to do that we do in our first releases means that we've put work at risk with no test against a real use universe, that is almost certainly creating the wrong quality at effort. We are not our end user, and our model of our end user is a superset of all potential concerns which is leading to defensive design and across the board that is increasing the difficulty of getting the site and project a step forward, and will increase the difficulty of keeping it going essentially forever, because we won't know if we didn't test which of the concerns we are upholding at a high level of professional quality we can back off of if they become too expensive to maintain as we get busier. We won't know, because on areas where we overshoot that seem to be working, we simply will not know how much more we are putting into it than as appropriate and necessary, and then just have to kind of keep at that level or worry that we will cause harm to the functioning system if we back off on something later.

This isn't about cutting corners, this is about putting corners in the right place which is more easily discovered from the not good enough side than it is from the too good side when you are working on a novel effort under sui generis circumstances. Craft is not appropriate in response to an emerging and changing crisis, because craft is derived from long experience and thus predictable needs and outcomes.

I seem to have written a novel in here I'm going to stop now, it seems like as a group one of the things I'm feeling an extremely urgent desire for us to do is to find a much lower consensus quality target than is emerging naturally from our process. I believe we are trying to do too many things before release and we are trying to do them far too well.

All that said, I still think we should have alt text on our images and whatnot 😅

**Comment by mfeif** [comment]
I hear that sentiment, and I agree. It's in my nature to be a little too cautious.

I do think having the feedback is still good, so it can be "registered" and we can loop back to it after our minimal published thing is live.

Thanks both. And thanks for testing, Will.
